import uniqueId from 'lodash.uniqueid';

import { Svg } from 'shared/components';
import { ItemInputTypes } from 'shared/types';

export const items = [
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.SingleSelection,
    name: 'Item 1',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: false,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.MultipleSelection,
    name: 'Item 2',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Date,
    name: 'Item 3',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: false,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Drawing,
    name: 'Item 4',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: false,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Audio,
    name: 'Item 5',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: false,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.AudioPlayer,
    name: 'Item 6',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: false,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Geolocation,
    name: 'Item 7',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: false,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Message,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.MultipleSelectionPerRow,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.NumberSelection,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Photo,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.SingleSelectionPerRow,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Slider,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.SliderRows,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Text,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.TimeRange,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
  {
    id: uniqueId(),
    itemsInputType: ItemInputTypes.Video,
    name: 'Item 8',
    body: 'This is the item text the quick brown fox jumps over the lazy dog ',
    hidden: true,
    settings: [],
  },
];

export const itemsTypeIcons = {
  [ItemInputTypes.SingleSelection]: <Svg id="radio-button-outline" />,
  [ItemInputTypes.MultipleSelection]: <Svg id="checkbox-multiple-filled" />,
  [ItemInputTypes.Slider]: <Svg id="slider-outline" />,
  [ItemInputTypes.Date]: <Svg id="calendar" />,
  [ItemInputTypes.NumberSelection]: <Svg id="number-selection" />,
  [ItemInputTypes.TimeRange]: <Svg id="clock" />,
  [ItemInputTypes.SingleSelectionPerRow]: <Svg id="single-selection-per-row" />,
  [ItemInputTypes.MultipleSelectionPerRow]: <Svg id="multiple-selection-per-row" />,
  [ItemInputTypes.SliderRows]: <Svg id="slider-rows" />,
  [ItemInputTypes.Text]: <Svg id="text" />,
  [ItemInputTypes.Drawing]: <Svg id="drawing" />,
  [ItemInputTypes.Photo]: <Svg id="photo" />,
  [ItemInputTypes.Video]: <Svg id="video" />,
  [ItemInputTypes.Geolocation]: <Svg id="geolocation" />,
  [ItemInputTypes.Audio]: <Svg id="audio" />,
  [ItemInputTypes.Message]: <Svg id="quote" />,
  [ItemInputTypes.AudioPlayer]: <Svg id="audio-player" />,
};
