import { ItemResponseType } from 'shared/consts';

export const UNSUPPORTED_ITEMS = [
  ItemResponseType.Date,
  ItemResponseType.Audio,
  ItemResponseType.AudioPlayer,
  ItemResponseType.Drawing,
  ItemResponseType.Geolocation,
  ItemResponseType.Message,
  ItemResponseType.Photo,
  ItemResponseType.Video,
  ItemResponseType.TimeRange,
  ItemResponseType.MultipleSelectionPerRow,
  ItemResponseType.SingleSelectionPerRow,
  ItemResponseType.SliderRows,
  ItemResponseType.NumberSelection,
  ItemResponseType.Flanker,
  ItemResponseType.StabilityTracker,
  ItemResponseType.TouchPractice,
  ItemResponseType.TouchTest,
  ItemResponseType.ABTrailsMobileFirst,
  ItemResponseType.ABTrailsMobileSecond,
  ItemResponseType.ABTrailsMobileThird,
  ItemResponseType.ABTrailsMobileFourth,
  ItemResponseType.ABTrailsTabletFirst,
  ItemResponseType.ABTrailsTabletSecond,
  ItemResponseType.ABTrailsTabletThird,
  ItemResponseType.ABTrailsTabletFourth,
];
