import uniqueId from 'lodash.uniqueid';

import { variables } from 'styles/variables';

import { CalendarEvent } from './Calendar.types';

export const LENGTH_TO_SET_ID_IS_HIDDEN = 2;
export const LENGTH_TO_FILTER_DAYS_EVENTS = 3;

export const mockedEvents: CalendarEvent[] = [
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-1',
    title: 'Daily Journal',
    start: new Date(2023, 0, 31, 0, 0, 0),
    end: new Date(2023, 0, 31, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-2',
    title: 'Pre-questionnaire',
    start: new Date(2023, 0, 31, 0, 0, 0),
    end: new Date(2023, 0, 31, 24, 0, 0),
    backgroundColor: variables.palette.green_alfa30,
    endAlertIcon: true,
    startFlowIcon: true,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-3',
    title: 'Daily Journal',
    start: new Date(2023, 1, 1, 0, 0, 0),
    end: new Date(2023, 1, 1, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-4',
    title: 'Pre-questionnaire',
    start: new Date(2023, 1, 1, 8, 30, 0),
    end: new Date(2023, 1, 1, 12, 30, 0),
    backgroundColor: variables.palette.green_alfa30,
    alwaysAvailable: false,
    endAlertIcon: true,
    startFlowIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-5',
    title: 'Daily Journal',
    start: new Date(2023, 1, 2, 0, 0, 0),
    end: new Date(2023, 1, 2, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-39',
    title: 'Daily Journal',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-40',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-41',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-42',
    title: 'Daily Journal',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    backgroundColor: variables.palette.orange_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-43',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-45',
    title: 'Daily Journal 999',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    backgroundColor: variables.palette.yellow_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16-2',
    title: 'Morning Assessment new',
    start: new Date(2023, 1, 13, 5, 0, 0),
    end: new Date(2023, 1, 13, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-2122',
    title: 'Emotional Support 99999',
    start: new Date(2023, 1, 23, 16, 0, 0),
    end: new Date(2023, 1, 23, 23, 59, 59),
    alwaysAvailable: false,
    backgroundColor: variables.palette.yellow_alfa30,
    isHidden: false,
    eventSpanAfter: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-2122',
    title: 'Emotional Support 99999',
    start: new Date(2023, 1, 24, 0, 0, 0),
    end: new Date(2023, 1, 24, 14, 0, 59),
    alwaysAvailable: false,
    backgroundColor: variables.palette.yellow_alfa30,
    isHidden: false,
    eventSpanBefore: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-21',
    title: 'Emotional Support',
    start: new Date(2023, 1, 22, 0, 0, 0),
    end: new Date(2023, 1, 22, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-22',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 22, 0, 0, 0),
    end: new Date(2023, 1, 22, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-6',
    title: 'Daily Journal',
    start: new Date(2023, 1, 22, 0, 0, 0),
    end: new Date(2023, 1, 22, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-7',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 22, 0, 0, 0),
    end: new Date(2023, 1, 22, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-8',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 22, 0, 0, 0),
    end: new Date(2023, 1, 22, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-9',
    title: 'Daily Journal',
    start: new Date(2023, 1, 22, 0, 0, 0),
    end: new Date(2023, 1, 22, 24, 0, 0),
    backgroundColor: variables.palette.orange_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-10',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 22, 0, 0, 0),
    end: new Date(2023, 1, 22, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-11',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 22, 7, 0, 0),
    end: new Date(2023, 1, 22, 8, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: false,
    isHidden: false,
    startFlowIcon: true,
    endAlertIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-12',
    title: 'Daily Journal 999',
    start: new Date(2023, 1, 22, 7, 0, 0),
    end: new Date(2023, 1, 22, 7, 20, 0),
    backgroundColor: variables.palette.yellow_alfa30,
    alwaysAvailable: false,
    allDayEvent: false,
    isHidden: false,
    startFlowIcon: true,
    endAlertIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-13',
    title:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
    start: new Date(2023, 1, 22, 5, 10, 0),
    end: new Date(2023, 1, 22, 5, 20, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-13999',
    title:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
    start: new Date(2023, 1, 22, 5, 30, 0),
    end: new Date(2023, 1, 22, 6, 0, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.orange,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-155',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 20, 0),
    end: new Date(2023, 1, 22, 9, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-18',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 22, 10, 30, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-15',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16-555',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 11, 50, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-177',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-155',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 20, 0),
    end: new Date(2023, 1, 22, 9, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-18',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 22, 10, 30, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-15',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16-555',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 11, 50, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-177',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-155',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 20, 0),
    end: new Date(2023, 1, 22, 9, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-18',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 22, 10, 30, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-15',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16-555',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 11, 50, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-177',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-155',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 20, 0),
    end: new Date(2023, 1, 22, 9, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-18',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 22, 10, 30, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-15',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16-555',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 11, 50, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-177',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-155',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 20, 0),
    end: new Date(2023, 1, 22, 9, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-18',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 22, 10, 30, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-15',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16-555',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 11, 50, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-177',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-155',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 20, 0),
    end: new Date(2023, 1, 22, 9, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-18',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 22, 10, 30, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-15',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16-555',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 11, 50, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-177',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-155',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 20, 0),
    end: new Date(2023, 1, 22, 9, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-18',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 22, 10, 30, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-15',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16-555',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 11, 50, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-177',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 22, 8, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
    startFlowIcon: true,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-155',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 22, 8, 20, 0),
    end: new Date(2023, 1, 22, 9, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 22, 9, 30, 0),
    end: new Date(2023, 1, 22, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 10, 20, 0),
    end: new Date(2023, 1, 22, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-1789',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 22, 21, 20, 0),
    end: new Date(2023, 1, 22, 23, 40, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-1899',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 22, 23, 5, 0),
    end: new Date(2023, 1, 22, 23, 55, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-39-1',
    title: 'Daily Journal',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-40-1',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-41-1',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-42-1',
    title: 'Daily Journal',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    backgroundColor: variables.palette.orange_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-43-1',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-45-1',
    title: 'Daily Journal 999',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    backgroundColor: variables.palette.yellow_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-19',
    title: 'One Day Month EventContainerWrapper',
    start: new Date(2023, 1, 25, 5, 30, 0),
    end: new Date(2023, 1, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.blue_alfa30,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-20',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 25, 8, 30, 0),
    end: new Date(2023, 1, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-23',
    title: 'Emotional Support',
    start: new Date(2023, 1, 17, 0, 0, 0),
    end: new Date(2023, 1, 17, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-24',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 17, 0, 0, 0),
    end: new Date(2023, 1, 17, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-25',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 18, 0, 0, 0),
    end: new Date(2023, 1, 18, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-26',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-27',
    title: 'Daily Journal',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-28',
    title: 'Midday Assessment',
    start: new Date(2023, 8, 25, 13, 30, 0),
    end: new Date(2023, 8, 25, 20, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.orange,
    scheduledBackground: variables.palette.orange_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-29',
    title: 'Morning Assessment',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-30',
    title: 'Morning Assessment 2',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-31',
    title: 'Morning Assessment 3',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-32',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-33',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-34',
    title: 'Emotional Support',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-35',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-36',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-37',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: uniqueId('event-'),
    resourceId: 'res-id-38',
    title: 'Incentive Activity 55',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
];
