import { variables } from 'styles/variables';

import { CalendarEvent } from './Calendar.types';

export const mockedEvents: CalendarEvent[] = [
  {
    id: 'daily-journal-id',
    title: 'Daily Journal',
    start: new Date(2023, 0, 31, 0, 0, 0),
    end: new Date(2023, 0, 31, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'pre-questionnaire-id',
    title: 'Pre-questionnaire',
    start: new Date(2023, 0, 31, 0, 0, 0),
    end: new Date(2023, 0, 31, 24, 0, 0),
    backgroundColor: variables.palette.green_alfa30,
    endAlertIcon: true,
    startFlowIcon: true,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'daily-journal-id',
    title: 'Daily Journal',
    start: new Date(2023, 1, 1, 0, 0, 0),
    end: new Date(2023, 1, 1, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'pre-questionnaire-id',
    title: 'Pre-questionnaire',
    start: new Date(2023, 1, 1, 8, 30, 0),
    end: new Date(2023, 1, 1, 12, 30, 0),
    backgroundColor: variables.palette.green_alfa30,
    alwaysAvailable: false,
    endAlertIcon: true,
    startFlowIcon: true,
    isHidden: false,
  },
  {
    id: 'daily-journal-id',
    title: 'Daily Journal',
    start: new Date(2023, 1, 2, 0, 0, 0),
    end: new Date(2023, 1, 2, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'daily-journal-id',
    title: 'Daily Journal',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: true,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'daily-journal-id',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id-2',
    title: 'Morning Assessment 555',
    start: new Date(2023, 1, 14, 5, 10, 0),
    end: new Date(2023, 1, 14, 6, 20, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 14, 8, 30, 0),
    end: new Date(2023, 1, 14, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 14, 8, 30, 0),
    end: new Date(2023, 1, 14, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 14, 9, 30, 0),
    end: new Date(2023, 1, 14, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 14, 10, 20, 0),
    end: new Date(2023, 1, 14, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id-99',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 14, 10, 30, 0),
    end: new Date(2023, 1, 14, 22, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: 'one-day-id',
    title: 'One Day Month EventWrapper',
    start: new Date(2023, 1, 25, 5, 30, 0),
    end: new Date(2023, 1, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.blue_alfa30,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 25, 8, 30, 0),
    end: new Date(2023, 1, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'emotional-support-id',
    title: 'Emotional Support',
    start: new Date(2023, 1, 16, 0, 0, 0),
    end: new Date(2023, 1, 16, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 16, 0, 0, 0),
    end: new Date(2023, 1, 16, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'emotional-support-id',
    title: 'Emotional Support',
    start: new Date(2023, 1, 17, 0, 0, 0),
    end: new Date(2023, 1, 17, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 17, 0, 0, 0),
    end: new Date(2023, 1, 17, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 18, 0, 0, 0),
    end: new Date(2023, 1, 18, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'daily-journal-id',
    title: 'Daily Journal',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'midday-assessment-id',
    title: 'Midday Assessment',
    start: new Date(2023, 8, 25, 13, 30, 0),
    end: new Date(2023, 8, 25, 20, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.orange,
    scheduledBackground: variables.palette.orange_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment 2',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment 3',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'morning-assessment-id',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'emotional-support-id',
    title: 'Emotional Support',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: 'incentive-activity-id',
    title: 'Incentive Activity 55',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
];
