import { variables } from 'styles/variables';

import { CalendarEvent } from './Calendar.types';

export const LENGTH_TO_SET_ID_IS_HIDDEN = 2;
export const LENGTH_TO_FILTER_DAYS_EVENTS = 4;

export const mockedEvents: CalendarEvent[] = [
  {
    id: '1',
    resourceId: '1',
    title: 'Daily Journal',
    start: new Date(2023, 0, 31, 0, 0, 0),
    end: new Date(2023, 0, 31, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '2',
    resourceId: '2',
    title: 'Pre-questionnaire',
    start: new Date(2023, 0, 31, 0, 0, 0),
    end: new Date(2023, 0, 31, 24, 0, 0),
    backgroundColor: variables.palette.green_alfa30,
    endAlertIcon: true,
    startFlowIcon: true,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '3',
    resourceId: '3',
    title: 'Daily Journal',
    start: new Date(2023, 1, 1, 0, 0, 0),
    end: new Date(2023, 1, 1, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '4',
    resourceId: '4',
    title: 'Pre-questionnaire',
    start: new Date(2023, 1, 1, 8, 30, 0),
    end: new Date(2023, 1, 1, 12, 30, 0),
    backgroundColor: variables.palette.green_alfa30,
    alwaysAvailable: false,
    endAlertIcon: true,
    startFlowIcon: true,
    isHidden: false,
  },
  {
    id: '5',
    resourceId: '5',
    title: 'Daily Journal',
    start: new Date(2023, 1, 2, 0, 0, 0),
    end: new Date(2023, 1, 2, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '39',
    resourceId: '39',
    title: 'Daily Journal',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: true,
  },
  {
    id: '40',
    resourceId: '40',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '41',
    resourceId: '41',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '42',
    resourceId: '42',
    title: 'Daily Journal',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    backgroundColor: variables.palette.orange_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: true,
  },
  {
    id: '43',
    resourceId: '43',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '45',
    resourceId: '45',
    title: 'Daily Journal 999',
    start: new Date(2023, 1, 13, 0, 0, 0),
    end: new Date(2023, 1, 13, 24, 0, 0),
    backgroundColor: variables.palette.yellow_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '16-2',
    resourceId: '16-2',
    title: 'Morning Assessment new',
    start: new Date(2023, 1, 13, 5, 0, 0),
    end: new Date(2023, 1, 13, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '6',
    resourceId: '6',
    title: 'Daily Journal',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: true,
  },
  {
    id: '7',
    resourceId: '7',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '8',
    resourceId: '8',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '9',
    resourceId: '9',
    title: 'Daily Journal',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    backgroundColor: variables.palette.orange_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: true,
  },
  {
    id: '10',
    resourceId: '10',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '11',
    resourceId: '11',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '12',
    resourceId: '12',
    title: 'Daily Journal 999',
    start: new Date(2023, 1, 14, 0, 0, 0),
    end: new Date(2023, 1, 14, 24, 0, 0),
    backgroundColor: variables.palette.yellow_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '13',
    resourceId: '13',
    title: 'Morning Assessment 555',
    start: new Date(2023, 1, 14, 5, 10, 0),
    end: new Date(2023, 1, 14, 6, 20, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '14',
    resourceId: '14',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 14, 8, 30, 0),
    end: new Date(2023, 1, 14, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '15',
    resourceId: '15',
    title: 'Morning Assessment 2',
    start: new Date(2023, 1, 14, 8, 30, 0),
    end: new Date(2023, 1, 14, 13, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.green,
    scheduledBackground: variables.palette.green_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '16',
    resourceId: '16',
    title: 'Morning Assessment 3',
    start: new Date(2023, 1, 14, 9, 30, 0),
    end: new Date(2023, 1, 14, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '17',
    resourceId: '17',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 1, 14, 10, 20, 0),
    end: new Date(2023, 1, 14, 15, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.blue,
    scheduledBackground: variables.palette.blue_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: '18',
    resourceId: '18',
    title: 'Morning Assessment 5 long very long',
    start: new Date(2023, 1, 14, 10, 30, 0),
    end: new Date(2023, 1, 14, 22, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.red,
    scheduledBackground: variables.palette.red_alfa30,
    endAlertIcon: false,
    isHidden: false,
  },
  {
    id: '39-1',
    resourceId: '39-1',
    title: 'Daily Journal',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: true,
  },
  {
    id: '40-1',
    resourceId: '40-1',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '41-1',
    resourceId: '41-1',
    title: 'Daily Journal 123',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '42-1',
    resourceId: '42-1',
    title: 'Daily Journal',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    backgroundColor: variables.palette.orange_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: true,
  },
  {
    id: '43-1',
    resourceId: '43-1',
    title: 'Incentive Activity 55',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    startFlowIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '45-1',
    resourceId: '45-1',
    title: 'Daily Journal 999',
    start: new Date(2023, 1, 21, 0, 0, 0),
    end: new Date(2023, 1, 21, 24, 0, 0),
    backgroundColor: variables.palette.yellow_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '19',
    resourceId: '19',
    title: 'One Day Month EventContainerWrapper',
    start: new Date(2023, 1, 25, 5, 30, 0),
    end: new Date(2023, 1, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.blue_alfa30,
    isHidden: false,
  },
  {
    id: '20',
    resourceId: '20',
    title: 'Morning Assessment',
    start: new Date(2023, 1, 25, 8, 30, 0),
    end: new Date(2023, 1, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '21',
    resourceId: '21',
    title: 'Emotional Support',
    start: new Date(2023, 1, 16, 0, 0, 0),
    end: new Date(2023, 1, 16, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '22',
    resourceId: '22',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 16, 0, 0, 0),
    end: new Date(2023, 1, 16, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '23',
    resourceId: '23',
    title: 'Emotional Support',
    start: new Date(2023, 1, 17, 0, 0, 0),
    end: new Date(2023, 1, 17, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '24',
    resourceId: '24',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 17, 0, 0, 0),
    end: new Date(2023, 1, 17, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '25',
    resourceId: '25',
    title: 'Incentive Activity',
    start: new Date(2023, 1, 18, 0, 0, 0),
    end: new Date(2023, 1, 18, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '26',
    resourceId: '26',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '27',
    resourceId: '27',
    title: 'Daily Journal',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    backgroundColor: variables.palette.blue_alfa30,
    alwaysAvailable: false,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '28',
    resourceId: '28',
    title: 'Midday Assessment',
    start: new Date(2023, 8, 25, 13, 30, 0),
    end: new Date(2023, 8, 25, 20, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.orange,
    scheduledBackground: variables.palette.orange_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '29',
    resourceId: '29',
    title: 'Morning Assessment',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '30',
    resourceId: '30',
    title: 'Morning Assessment 2',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '31',
    resourceId: '31',
    title: 'Morning Assessment 3',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '32',
    resourceId: '32',
    title: 'Morning Assessment 4 long very long',
    start: new Date(2023, 8, 25, 8, 30, 0),
    end: new Date(2023, 8, 25, 12, 30, 0),
    alwaysAvailable: false,
    backgroundColor: variables.palette.white,
    scheduledColor: variables.palette.yellow,
    scheduledBackground: variables.palette.yellow_alfa30,
    endAlertIcon: true,
    isHidden: false,
  },
  {
    id: '33',
    resourceId: '33',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '34',
    resourceId: '34',
    title: 'Emotional Support',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.blue,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '35',
    resourceId: '35',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '36',
    resourceId: '36',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '37',
    resourceId: '37',
    title: 'Incentive Activity',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
  {
    id: '38',
    resourceId: '38',
    title: 'Incentive Activity 55',
    start: new Date(2023, 8, 25, 0, 0, 0),
    end: new Date(2023, 8, 25, 24, 0, 0),
    alwaysAvailable: true,
    backgroundColor: variables.palette.green,
    endAlertIcon: true,
    allDayEvent: true,
    isHidden: false,
  },
];
