export const MAX_VISIBLE_EVENTS_WEEK_VIEW = 5;
export const MAX_VISIBLE_EVENTS_DAY_VIEW = 30;
export const LEFT_OFFSET_COEFFICIENT_WEEK_VIEW = 17;
export const LEFT_OFFSET_COEFFICIENT_DAY_VIEW = 3.25;
export const LEFT_START_VAL_WEEK_VIEW = 1;
export const LEFT_START_VAL_DAY_VIEW = 0;
export const VALUE_DECREASING_CONTAINER_WIDTH_WEEK_VIEW = '1.6rem';
export const VALUE_DECREASING_CONTAINER_WIDTH_DAY_VIEW = '8rem';
