export const DEFAULT_START_TIME = '00:00';
export const DEFAULT_END_TIME = '23:59';
export const DEFAULT_TIMER_DURATION = '01:00';
export const DEFAULT_IDLE_TIME = '00:01';
export const SECONDS_TO_MILLISECONDS_MULTIPLIER = 1000;
export const DEFAULT_ACTIVITY_INCOMPLETE_VALUE = 0;
export const ONCE_ACTIVITY_INCOMPLETE_LIMITATION = 2;
