export type AuditEvent = {
  '@timestamp': string;
  'error.type': string | null;
  'event.action': string;
  'event.id': string;
  'event.kind': string;
  'event.outcome': string;
  'event.module': string;
  'event.dataset': string;
  'service.name': string;
  'service.environment': string;
  'user.id': string;
  'user.email': string | null;
  'user.roles': string[] | null;
  'user.target.id': string | null;
  'user.target.email': string | null;
  'user.target.roles': string[] | null;
  'client.ip': string;
  'http.request.id': string;
  'http.request.method': string;
  'http.response.status_code': number;
  'trace.id': string;
  'url.path': string;
  'url.query': string;
  'user_agent.original': string;
  'file.path': string | null;
  'curious.applet_id': string[] | null;
  'curious.subject_id': string[] | null;
  'curious.flow_id': string[] | null;
  'curious.activity_id': string[] | null;
  'curious.submit_id': string[] | null;
  'curious.answer_id': string[] | null;
  'event.category': string[];
  'event.type': string[];
};
