name: Build and Deploy to UAT

on:
#  push:
#    tags:
#      - "*-rc[0-9]+"
  release:
    types:
      - prereleased
  workflow_dispatch:
    inputs:
      target-ref:
        description: The RC tag to use
        required: true
        type: string

concurrency:
  cancel-in-progress: true
  group: admin-build-deploy-uat

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  ref:
    name: Get target ref
    runs-on: ubuntu-latest
    outputs:
      target-ref: ${{ steps.ref.outputs.ref }}
    steps:
      - id: ref
        name: Select Ref
        # was: ${{ github.ref_name }}
        run: |
          TARGET_REF="${{ github.event.inputs.target-ref }}"
          # Use shell parameter expansion to provide a default value if input is unset or empty
          # github.ref_name will be used if the input is not provided or empty
          # Remove "refs/heads/" or "refs/tags/" if present in github.ref_name
          TARGET_REF=${TARGET_REF:-$(echo "${{ github.event.release.tag_name }}" | sed 's/refs\/heads\///g' | sed 's/refs\/tags\///g')} 
          echo "Target reference: $TARGET_REF"
          echo "ref=$TARGET_REF" >> $GITHUB_OUTPUT

  build-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/_build-deploy.yaml
    needs: ref
    with:
      env-name: uat
      version: ${{ needs.ref.outputs.target-ref }}
      git-ref: ${{ needs.ref.outputs.target-ref }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK_DEPLOY_TO_UAT }}
